spring.datasource.url: jdbc:mysql://localhost:3306/todo_list
spring.datasource.username: root
spring.datasource.password: 935117256SQL
spring.jpa.hibernate.ddl-auto: none
spring.thymeleaf.cache: false
spring.template.cache: false